version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
hooks:
  AfterInstall:
    - location: scrips/create.log-stream.sh
      timeout: 300
    - location: scripts/after.install.sh
      timeout: 300
