version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm ci
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION" >> build.sh
      - echo "Commit ID - $CODEBUILD_RESOLVED_SOURCE_VERSION"  # 커밋 ID 출력
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build.sh
    - '**/*'
  name: build-$(date +%Y-%m-%d)
