# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [main, local]
  push:
    branches: [local]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: npm ci
        if: ${{ always() }}
      - run: npm test
        if: ${{ always() }}
      - run: npm run test-e2e
        env:
          NODE_ENV: ${{secrets.NODE_ENV}}
          PORT: ${{secrets.PORT}}
          AUTH_PATH: ${{secrets.AUTH_PATH}}
          FRONT_URL_PROD: ${{secrets.FRONT_URL_PROD}}
          FRONT_URL2_PROD: ${{secrets.FRONT_URL2_PROD}}
          FRONT_URL_DEV: ${{secrets.FRONT_URL_DEV}}
          FRONT_URL2_DEV: ${{secrets.FRONT_URL2_DEV}}
          FRONT_URL_LOCAL: ${{secrets.FRONT_URL_LOCAL}}
          SWAGGER_ID: ${{secrets.SWAGGER_ID}}
          SWAGGER_PW: ${{secrets.SWAGGER_PW}}
          SWAGGER_JSON: ${{secrets.SWAGGER_JSON}}
          SWAGGER_PATH_DEV: ${{secrets.SWAGGER_PATH_DEV}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_NAME: ${{secrets.DB_NAME}}
          REDIS_HOST: ${{secrets.REDIS_HOST}}
          REIDS_PORT: ${{secrets.REIDS_PORT}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
          REDIS_TTL: ${{secrets.REDIS_TTL}}
          REDIS_DB_NUM: ${{secrets.REDIS_DB_NUM}}
          REDIS_TEST_DB_NUM: ${{secrets.REDIS_TEST_DB_NUM}}
          JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
          JWT_EXPRIED_TIME: ${{secrets.JWT_EXPRIED_TIME}}
          KAKAO_CLIENT_ID: ${{secrets.KAKAO_CLIENT_ID}}
          KAKAO_CALLBACK_URL: ${{secrets.KAKAO_CALLBACK_URL}}
          KAKAO_CLIENT_SECRET_KEY: ${{secrets.KAKAO_CLIENT_SECRET_KEY}}
          RIOT_API_KEY: ${{secrets.RIOT_API_KEY}}
          DB_NAME_TEST: ${{secrets.DB_NAME_TEST}}
          TEST_NICKNAME: ${{secrets.TEST_NICKNAME}}
          TEST_IMG: ${{secrets.TEST_IMG}}
      - run: npm run build --if-present
        if: ${{ always() }}
